### ISSUE TITLE
小米 6 Global 刷完之后 APP FC

### ISSUE THREAD

**Issue by A1exInamin** [linusyang92/mipay-extract#4]
MIUI 版本: MIUI 9 Global 8.4.19
提取固件版本: MIUI 9 China 8.4.19 / 8.5.8
表现: 使用 TWRP 刷入成功之后重启，小米钱包及小米智能卡均无法运行，错误 log 如下:

小米智能卡: https://paste.ubuntu.com/p/gkFwrGDDvx/
小米钱包: https://paste.ubuntu.com/p/yZXMKzhJwW/

**Comment by chestermax01** [comment]
确实不行

**Comment by chestermax01** [comment]
小米6欧盟版8.5.8制作刷了钱包和公交卡包以后会报这个错，还缺什么？
<pre>
java.lang.RuntimeException: Unable to instantiate application com.mipay.wallet.App: java.lang.ClassNotFoundException: Didn't find class "com.mipay.wallet.App" on path: DexPathList[[zip file "/system/app/Mipay/Mipay.apk"],nativeLibraryDirectories=[/system/app/Mipay/lib/arm64, /system/fake-libs64, /system/app/Mipay/Mipay.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at android.app.LoadedApk.makeApplication(Unknown Source:171)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1032)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:502)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:142)
	at android.app.ActivityThread.main(Unknown Source:71)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:200)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mipay.wallet.App" on path: DexPathList[[zip file "/system/app/Mipay/Mipay.apk"],nativeLibraryDirectories=[/system/app/Mipay/lib/arm64, /system/fake-libs64, /system/app/Mipay/Mipay.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newApplication(Unknown Source:0)
	at android.app.LoadedApk.makeApplication(Unknown Source:68)
	... 9 more
	Suppressed: java.io.IOException: No original dex files found for dex location /system/app/Mipay/Mipay.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(Unknown Source:4)
		at android.app.ApplicationLoaders.getClassLoader(Unknown Source:47)
		at android.app.ApplicationLoaders.getClassLoader(Unknown Source:8)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(Unknown Source:230)
		at android.app.LoadedApk.getClassLoader(Unknown Source:6)
		at android.app.LoadedApk.getResources(Unknown Source:26)
		at android.app.ContextImpl.createAppContext(Unknown Source:24)
		at android.app.ActivityThread.handleBindApplication(Unknown Source:701)
		... 8 more
</pre>

**Comment by seanliu96** [comment]
因为global版和china版调用的api有些许差别，所以最新版的china版和global版可能并不能完全兼容。
请抽取china版的8.3.15，或者使用下面的zip。

[mipay-MI6-8.3.15.zip](https://github.com/linusyang92/mipay-extract/files/2048462/mipay-MI6-8.3.15.zip)

**Comment by chestermax01** [comment]
欧盟版用8.3.15的也不行，依然是这个错

**Comment by seanliu96** [comment]
@chestermax01 我没用过EU版，所以没有测试过。理论上多试旧的china版就可以。

**Comment by chestermax01** [comment]
@A1exInamin 你试过了吗？

**Comment by A1exInamin** [comment]
我是在网上找的 8.3.1 的卡刷包，现在能正常使用

2018年5月31日(木) 15:11 chestermax01 <notifications@github.com>:

**Comment by chestermax01** [comment]
8.3.1的也不行，看来小米6欧盟版还额外砍掉了什么东西。。。

**Comment by linusyang** [comment]
@chestermax01 @A1exInamin  Just tested working perfectly on my Mix 2, OS version is xiaomi.eu 8.6.14. Mi Pay is extracted from MIUI 10 China ROM 8.6.14 using latest script in this repo. Packages for Mix 2 can be found in releases.

**Comment by luciszh** [comment]
@chestermax01 @linusyang  找到解决方法了吗？ 我跟你报一样的错 8.6.21 EU 米6 国内同版本提取的mipay

**Comment by luciszh** [comment]
![437515030](https://user-images.githubusercontent.com/23099978/42020664-1a89a912-7aeb-11e8-83b5-c640e383c038.jpg)
![568523818](https://user-images.githubusercontent.com/23099978/42020665-1ad31cc8-7aeb-11e8-8edc-9d9aeebad4c4.jpg)
![721064541](https://user-images.githubusercontent.com/23099978/42020667-1b0af0f8-7aeb-11e8-9c0c-5b06b2f9f72d.jpg)
另外 recovery里刷入eu rom后 无法直接刷入mipay 错误代码见图片 需要刷强制解密或者取消system挂载然后再挂载system之后 mipay才能正常刷入 但是开机之后依然报错闪退

**Comment by linusyang** [comment]
@luciszh FC我估计是multi-dex class的问题，小米6的mipay应该是有多个classes.dex，但是脚本没有都提取，我可以加个判断。还有可能是dalvik-cache没有刷新，导致class对不上，这个我可以在刷机包里的脚本加一下。

你那个刷失败是因为recovery的原因，/system分区挂载不上，再重启一次到recovery，再刷应该能解决。

**Comment by luciszh** [comment]
@linusyang  麻烦你了 还有eufix-MI6 我后面就没刷 刷完之后进系统 priv-app里牵扯到的app全部FC

**Comment by luciszh** [comment]
为了测试 专门又下载了 MIUI9 8.5.8 EU和国内对应版本的提取mipay 然而还是fc 且报错内容都是一样的 奇怪了

**Comment by luciszh** [comment]
@linusyang 上次反馈完这个问题 使用了更新后的mipay extract工具 提取后刷入mi6依然报相同的错误 不过无意中发现了这个博主的办法 https://www.yipkwong.com/2018/06/06/167/ 按照他的教程提取出的文件 在米6上是可以正常使用的 他的提取文件链接 https://pan.baidu.com/s/1tpGOCasUteY0daseorr6VQ 提取码：rapp 能否请你对比一下 这个文件和用extract工具提取出的米6文件有什么区别 或者能否借此修复一下extract工具提取米6的bug 谢谢！

**Comment by linusyang** [comment]
@luciszh I think the process is exact the same. Try the latest version of mipay-extract and 8.8.9 version of Mi 6:

http://bigota.d.miui.com/8.8.9/miui_MI6_8.8.9_90988291c1_8.0.zip

Backup your data and flash the `mipay-MI6-8.8.9.zip`. No need to clean dalvik cache. The script now automatically does that.

Try and report any FC issues here. Thanks.

**Comment by luciszh** [comment]
@linusyang still cant work on mi6 8.8.16 version with the lastest version of mipay-extract
![](https://i.imgur.com/XANLBGa.png)![](https://i.imgur.com/ZsOFfaw.png)![](https://i.imgur.com/BonvdFe.png)

**Comment by luciszh** [comment]
我在extract工具提取出的system.img镜像文件里手动提取出了这些文件[mipay](https://drive.google.com/file/d/12woFvht2JBe73OGm7oMkaJSAKXNtjQFb/view?usp=drivesdk)
在/system/app路径中提取出Mipay,NextPay,TSMClient,UPTsmService四个软件包，直接整个文件夹提取出来，然后把TSMClient里面的lib文件夹删除，再在/system/lib64中提取一个libuptsmaddonmi.so文件 分别手动复制到对应文件夹中 将文件夹权限设定为0755，文件夹下所有的子文件夹也设置为0755,文件夹内文件都设置为0644后 重启后可以正常使用 但是直接用提取出的刷机包直接刷入就会出现如上条fc bug

**Comment by shunf4** [comment]
@luciszh @linusyang I compared 2 `Mipay.apk`'s from `mipay-MI6-8.8.16.zip` generated by the script by myself and `mipay-MIMIX2-8.8.9.zip` from release page and found that the paths of `classes.dex` were different: one under `.zip!/system/app/Mipay/oat/arm64/` and one under `zip!/`. Maybe the problem is here?

**Comment by shunf4** [comment]
solved after changing to China firmware 8.8.9 and copying all the `classes.dex` to `*.zip!/` (root path).
Under Windows Cygwin environment, `-k` option in `aapt` does not work in normal way.
Will create a PR to temporarily fix it later

**Comment by linusyang** [comment]
@shunf4 Thanks for the patch!
@luciszh Please retry with the latest scripts. Thanks!

**Comment by luciszh** [comment]
@shunf4 @linusyang Thanks for both of your work! Work fine on 8.8.23
