### ISSUE TITLE
[need help] Xiaomi 10 pro crash when --appvault patched

### ISSUE THREAD

**Issue by xspeed1989** [linusyang92/mipay-extract#63]
@linusyang92 
my os version 12.0.4
priv-app/PersonalAssistan will crashed  when click setting on bottom appvault

can you help me ? thanks

**Comment by xspeed1989** [comment]
this is log
```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.personalassistant/com.miui.personalassistant.ui.CardSettingsActivity}: java.lang.IllegalStateException: You need to use a miui theme (or descendant) with this activity.
 at android.app.ActivityThread.performLaunchActivity(Unknown Source:621)
 at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
 at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
 at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
 at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
 at android.os.Handler.dispatchMessage(Unknown Source:19)
 at android.os.Looper.loop(Unknown Source:249)
 at android.app.ActivityThread.main(Unknown Source:98)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:282)
Caused by: java.lang.IllegalStateException: You need to use a miui theme (or descendant) with this activity.
 at com.miui.internal.app.ActivityDelegate.installSubDecor(Unknown Source:437)
 at com.miui.internal.app.ActivityDelegate.onCreate(Unknown Source:3)
 at miui.app.Activity.onCreate(Unknown Source:5)
 at com.miui.personalassistant.ui.BaseActivity.onCreate(Unknown Source:0)
 at com.miui.personalassistant.ui.CardSettingsActivity.onCreate(Unknown Source:0)
 at android.app.Activity.performCreate(Unknown Source:19)
 at android.app.Activity.performCreate(Unknown Source:1)
 at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
 at android.app.ActivityThread.performLaunchActivity(Unknown Source:376)
 ... 11 more
```
